-- MySQL Script generated by MySQL Workbench
-- Sun Nov 30 16:22:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alquiler_autos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alquiler_autos` ;

-- -----------------------------------------------------
-- Schema alquiler_autos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alquiler_autos` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `alquiler_autos` ;

-- -----------------------------------------------------
-- Table `autos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `autos` (
  `id_auto` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `anio` INT(11) NOT NULL,
  `patente` VARCHAR(15) NOT NULL,
  `precio_por_dia` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'disponible',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_auto_UNIQUE` ON `autos` (`id_auto` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `patente_UNIQUE` ON `autos` (`patente` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_rol_UNIQUE` ON `roles` (`id_rol` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `fk_rol` INT(11) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuarios_rol` FOREIGN KEY (`fk_rol`) REFERENCES `roles`(`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `usuarios` (`id_usuario` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `correo_UNIQUE` ON `usuarios` (`correo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `reservas` (
  `id_reserva` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT(11) NOT NULL,
  `fk_auto` INT(11) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  `precio_total` DECIMAL(10,2) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `fk_reservas_usuario` FOREIGN KEY (`fk_usuario`) REFERENCES `usuarios`(`id_usuario`) ON DELETE CASCADE,
  CONSTRAINT `fk_reservas_auto` FOREIGN KEY (`fk_auto`) REFERENCES `autos`(`id_auto`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_reserva_UNIQUE` ON `reservas` (`id_reserva` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Initial Data: Roles
-- -----------------------------------------------------
INSERT INTO `roles` (`id_rol`, `nombre`) VALUES (1, 'admin');
INSERT INTO `roles` (`id_rol`, `nombre`) VALUES (2, 'cliente');

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
